services:
  cryptomsg-test-nginx:
    build: .
    container_name: cryptomsg-test-nginx
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./certs:/etc/nginx/certs:ro
    extra_hosts:
      # Для Linux: host.docker.internal -> host-gateway
      - "host.docker.internal:host-gateway"
